import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase-server";
import { advanceKnockoutMatch } from "@/lib/tournament/advance-knockout-match";

interface RouteContext {
  params: Promise<{
    id: string;
  }>;
}

/*
 * --------------------------------------------------
 * MATCH STAGE DETECTION
 * --------------------------------------------------
 *
 * IMPORTANT:
 *
 * Round Robin examples:
 *   Round 1
 *   Round 2
 *   Leg 1 - Round 1
 *   Leg 2 - Round 1
 *
 * Knockout examples:
 *   Round of 16
 *   Quarterfinal
 *   Quarterfinals
 *   Semifinal
 *   Semifinals
 *   Final
 *   Knockout
 *
 * We MUST NOT simply check whether the word
 * "round" exists because "Round of 16" is knockout.
 */

function getMatchStage(round: string | null): {
  isRoundRobin: boolean;
  isKnockout: boolean;
} {
  const value = (round ?? "")
    .toLowerCase()
    .trim();

  /*
   * -----------------------------------------------
   * ROUND ROBIN
   * -----------------------------------------------
   *
   * These are the fixture labels generated by
   * our Round Robin generator.
   */

  const isRoundRobin =
    /^round\s+\d+$/i.test(value) ||
    /^leg\s+\d+\s*-\s*round\s+\d+$/i.test(
      value
    );

  /*
   * -----------------------------------------------
   * KNOCKOUT
   * -----------------------------------------------
   */

  const isRoundOf =
    /^round\s+of\s+\d+$/i.test(value);

  const isQuarterfinal =
    value === "quarterfinal" ||
    value === "quarterfinals";

  const isSemifinal =
    value === "semifinal" ||
    value === "semifinals";

 const isFinal =
  value === "final";

const isThirdPlace =
  value === "3rd place" ||
  value === "third place" ||
  value === "third-place";

const isKnockout =
  isRoundOf ||
  isQuarterfinal ||
  isSemifinal ||
  isFinal ||
  isThirdPlace ||
  value.includes("knockout");
  return {
    isRoundRobin,
    isKnockout,
  };
}

/*
 * --------------------------------------------------
 * GET
 * --------------------------------------------------
 * Load one match.
 */

export async function GET(
  request: NextRequest,
  context: RouteContext
) {
  try {
    const { id } = await context.params;

    const matchId = Number(id);

    if (
      !matchId ||
      Number.isNaN(matchId)
    ) {
      return NextResponse.json(
        {
          success: false,
          message:
            "A valid match ID is required.",
        },
        { status: 400 }
      );
    }

    const supabase =
      await createClient();

    const {
  data: match,
  error,
} = await supabase
  .from("matches")
  .select(`
    *,
    player_a:players!matches_player_a_id_fkey (
      id,
      full_name,
      gamer_tag
    ),
    player_b:players!matches_player_b_id_fkey (
      id,
      full_name,
      gamer_tag
    ),
    team_a:teams!matches_team_a_id_fkey (
      id,
      team_name
    ),
    team_b:teams!matches_team_b_id_fkey (
      id,
      team_name
    )
  `)
  .eq("id", matchId)
  .single();

    if (error) {
      console.error(
        "Match lookup error:",
        error
      );

      return NextResponse.json(
        {
          success: false,
          message:
            "Failed to load match.",
          error:
            error.message,
          details:
            error.details,
          hint:
            error.hint,
          code:
            error.code,
        },
        { status: 500 }
      );
    }

    if (!match) {
      return NextResponse.json(
        {
          success: false,
          message:
            "Match not found.",
        },
        { status: 404 }
      );
    }

    return NextResponse.json({
      success: true,
      match,
    });
  } catch (error) {
    console.error(
      "GET match API error:",
      error
    );

    return NextResponse.json(
      {
        success: false,
        message:
          error instanceof Error
            ? error.message
            : "Unexpected server error.",
      },
      { status: 500 }
    );
  }
}

/*
 * --------------------------------------------------
 * PATCH
 * --------------------------------------------------
 * Update one match.
 */

export async function PATCH(
  request: NextRequest,
  context: RouteContext
) {
  try {
    const { id } = await context.params;

    const matchId = Number(id);

    if (
      !matchId ||
      Number.isNaN(matchId)
    ) {
      return NextResponse.json(
        {
          success: false,
          message:
            "A valid match ID is required.",
        },
        { status: 400 }
      );
    }

    const body =
      await request.json();

    console.log(
      "MATCH UPDATE REQUEST:",
      {
        matchId,
        body,
      }
    );

    const supabase =
      await createClient();

    /*
     * --------------------------------------------------
     * 1. LOAD EXISTING MATCH
     * --------------------------------------------------
     */

    const {
      data: existingMatch,
      error: existingMatchError,
    } = await supabase
      .from("matches")
      .select("*")
      .eq("id", matchId)
      .single();

    if (existingMatchError) {
      console.error(
        "Existing match lookup error:",
        existingMatchError
      );

      return NextResponse.json(
        {
          success: false,
          message:
            "Unable to find the match before updating.",
          error:
            existingMatchError.message,
          details:
            existingMatchError.details,
          hint:
            existingMatchError.hint,
          code:
            existingMatchError.code,
        },
        { status: 500 }
      );
    }

    if (!existingMatch) {
      return NextResponse.json(
        {
          success: false,
          message:
            "Match not found.",
        },
        { status: 404 }
      );
    }
    /*
 * --------------------------------------------------
 * 1B. CHECK TOURNAMENT STATUS
 * --------------------------------------------------
 *
 * Once the tournament is completed, its matches
 * become permanently locked.
 *
 * This prevents an administrator from changing
 * a historical match result and therefore changing
 * the tournament winner after completion.
 */

const {
  data: tournament,
  error: tournamentError,
} = await supabase
  .from("tournaments")
  .select("id, tournament_name, status")
  .eq("id", existingMatch.tournament_id)
  .single();

if (tournamentError) {
  console.error(
    "Tournament lookup error:",
    tournamentError
  );

  return NextResponse.json(
    {
      success: false,
      message:
        "Unable to verify tournament status before updating the match.",
      error: tournamentError.message,
    },
    { status: 500 }
  );
}

if (!tournament) {
  return NextResponse.json(
    {
      success: false,
      message:
        "The tournament associated with this match could not be found.",
    },
    { status: 404 }
  );
}

/*
 * --------------------------------------------------
 * TOURNAMENT COMPLETION LOCK
 * --------------------------------------------------
 */

if (
  tournament.status?.toLowerCase().trim() ===
  "completed"
) {
  return NextResponse.json(
    {
      success: false,
      locked: true,
      message:
        "This tournament has been completed. Match results are locked and can no longer be modified.",
      tournament: {
        id: tournament.id,
        tournament_name:
          tournament.tournament_name,
        status: tournament.status,
      },
    },
    { status: 403 }
  );
}

    /*
     * --------------------------------------------------
     * 2. DETERMINE MATCH STAGE
     * --------------------------------------------------
     */

    const {
      isRoundRobin,
      isKnockout,
    } =
      getMatchStage(
        existingMatch.round
      );

    console.log(
      "MATCH STAGE:",
      {
        matchId,
        round:
          existingMatch.round,
        isRoundRobin,
        isKnockout,
      }
    );

    /*
     * --------------------------------------------------
     * 3. DETERMINE PARTICIPANT TYPE
     * --------------------------------------------------
     */

    const isTeamMatch =
      existingMatch.team_a_id !== null ||
      existingMatch.team_b_id !== null;

    const isPlayerMatch =
      existingMatch.player_a_id !== null ||
      existingMatch.player_b_id !== null;

    if (
      !isTeamMatch &&
      !isPlayerMatch
    ) {
      return NextResponse.json(
        {
          success: false,
          message:
            "This match does not have valid participants.",
        },
        { status: 400 }
      );
    }

    if (
      isTeamMatch &&
      isPlayerMatch
    ) {
      return NextResponse.json(
        {
          success: false,
          message:
            "A match cannot contain both team and player participants.",
        },
        { status: 400 }
      );
    }

    /*
     * --------------------------------------------------
     * 4. PREPARE SCORES
     * --------------------------------------------------
     */

    const scoreTeamA =
      body.score_team_a === null ||
      body.score_team_a === ""
        ? null
        : Number(
            body.score_team_a
          );

    const scoreTeamB =
      body.score_team_b === null ||
      body.score_team_b === ""
        ? null
        : Number(
            body.score_team_b
          );

    /*
     * --------------------------------------------------
     * 5. VALIDATE NORMAL SCORES
     * --------------------------------------------------
     */

    if (
      scoreTeamA !== null &&
      (
        Number.isNaN(
          scoreTeamA
        ) ||
        scoreTeamA < 0
      )
    ) {
      return NextResponse.json(
        {
          success: false,
          message:
            "Participant A score must be a valid non-negative number.",
        },
        { status: 400 }
      );
    }

    if (
      scoreTeamB !== null &&
      (
        Number.isNaN(
          scoreTeamB
        ) ||
        scoreTeamB < 0
      )
    ) {
      return NextResponse.json(
        {
          success: false,
          message:
            "Participant B score must be a valid non-negative number.",
        },
        { status: 400 }
      );
    }

    /*
     * --------------------------------------------------
     * 6. STATUS
     * --------------------------------------------------
     */

    const status =
      body.status ||
      "Scheduled";

    /*
     * --------------------------------------------------
     * 7. WINNER
     * --------------------------------------------------
     */

    let winnerTeamId:
      number | null = null;

    let winnerPlayerId:
      number | null = null;

    /*
     * --------------------------------------------------
     * 8. COMPLETED MATCH LOGIC
     * --------------------------------------------------
     */

    if (
      status === "Completed"
    ) {
      /*
       * A completed match requires
       * both normal scores.
       */

      if (
        scoreTeamA === null ||
        scoreTeamB === null
      ) {
        return NextResponse.json(
          {
            success: false,
            message:
              "A completed match must have both participant scores.",
          },
          { status: 400 }
        );
      }

      /*
       * ==================================================
       * ROUND ROBIN
       * ==================================================
       *
       * Draws ARE allowed.
       *
       * Example:
       *
       * Player A 2
       * Player B 2
       *
       * Winner:
       * NONE
       */

      if (isRoundRobin) {
        /*
         * DRAW
         */

        if (
          scoreTeamA ===
          scoreTeamB
        ) {
          winnerTeamId =
            null;

          winnerPlayerId =
            null;
        }

        /*
         * PARTICIPANT A WINS
         */

        else if (
          scoreTeamA >
          scoreTeamB
        ) {
          if (isTeamMatch) {
            winnerTeamId =
              existingMatch.team_a_id;
          } else {
            winnerPlayerId =
              existingMatch.player_a_id;
          }
        }

        /*
         * PARTICIPANT B WINS
         */

        else {
          if (isTeamMatch) {
            winnerTeamId =
              existingMatch.team_b_id;
          } else {
            winnerPlayerId =
              existingMatch.player_b_id;
          }
        }
      }

      /*
       * ==================================================
       * KNOCKOUT
       * ==================================================
       *
       * Knockout matches MUST have a winner.
       *
       * Normal score can decide the winner.
       *
       * If normal score is tied, penalties are required.
       */

      else if (isKnockout) {
        /*
         * -----------------------------------------------
         * A WINS ON NORMAL SCORE
         * -----------------------------------------------
         */

        if (
          scoreTeamA >
          scoreTeamB
        ) {
          if (isTeamMatch) {
            winnerTeamId =
              existingMatch.team_a_id;
          } else {
            winnerPlayerId =
              existingMatch.player_a_id;
          }
        }

        /*
         * -----------------------------------------------
         * B WINS ON NORMAL SCORE
         * -----------------------------------------------
         */

        else if (
          scoreTeamB >
          scoreTeamA
        ) {
          if (isTeamMatch) {
            winnerTeamId =
              existingMatch.team_b_id;
          } else {
            winnerPlayerId =
              existingMatch.player_b_id;
          }
        }

        /*
         * -----------------------------------------------
         * NORMAL SCORE IS TIED
         * -----------------------------------------------
         */

        else {
          const penaltyAValue =
            body.penalty_score_a ??
            body.penalties_a ??
            null;

          const penaltyBValue =
            body.penalty_score_b ??
            body.penalties_b ??
            null;

          const penaltyA =
            penaltyAValue === null ||
            penaltyAValue === ""
              ? null
              : Number(
                  penaltyAValue
                );

          const penaltyB =
            penaltyBValue === null ||
            penaltyBValue === ""
              ? null
              : Number(
                  penaltyBValue
                );

          /*
           * VALIDATE PENALTY A
           */

          if (
            penaltyA !== null &&
            (
              Number.isNaN(
                penaltyA
              ) ||
              penaltyA < 0
            )
          ) {
            return NextResponse.json(
              {
                success: false,
                message:
                  "Participant A penalty score must be a valid non-negative number.",
              },
              { status: 400 }
            );
          }

          /*
           * VALIDATE PENALTY B
           */

          if (
            penaltyB !== null &&
            (
              Number.isNaN(
                penaltyB
              ) ||
              penaltyB < 0
            )
          ) {
            return NextResponse.json(
              {
                success: false,
                message:
                  "Participant B penalty score must be a valid non-negative number.",
              },
              { status: 400 }
            );
          }

          /*
           * BOTH PENALTY SCORES REQUIRED
           */

          if (
            penaltyA === null ||
            penaltyB === null
          ) {
            return NextResponse.json(
              {
                success: false,
                message:
                  "A tied knockout match requires penalty scores to determine the winner.",
              },
              { status: 400 }
            );
          }

          /*
           * PENALTIES CANNOT BE TIED
           */

          if (
            penaltyA ===
            penaltyB
          ) {
            return NextResponse.json(
              {
                success: false,
                message:
                  "Penalty scores cannot be tied in a completed knockout match.",
              },
              { status: 400 }
            );
          }

          /*
           * A WINS ON PENALTIES
           */

          if (
            penaltyA >
            penaltyB
          ) {
            if (isTeamMatch) {
              winnerTeamId =
                existingMatch.team_a_id;
            } else {
              winnerPlayerId =
                existingMatch.player_a_id;
            }
          }

          /*
           * B WINS ON PENALTIES
           */

          else {
            if (isTeamMatch) {
              winnerTeamId =
                existingMatch.team_b_id;
            } else {
              winnerPlayerId =
                existingMatch.player_b_id;
            }
          }
        }
      }

      /*
       * ==================================================
       * UNKNOWN STAGE
       * ==================================================
       *
       * We deliberately DO NOT treat an unknown stage
       * as knockout.
       *
       * Normal score decides the winner.
       *
       * This prevents accidental knockout behavior.
       */

      else {
        if (
          scoreTeamA >
          scoreTeamB
        ) {
          if (isTeamMatch) {
            winnerTeamId =
              existingMatch.team_a_id;
          } else {
            winnerPlayerId =
              existingMatch.player_a_id;
          }
        }

        else if (
          scoreTeamB >
          scoreTeamA
        ) {
          if (isTeamMatch) {
            winnerTeamId =
              existingMatch.team_b_id;
          } else {
            winnerPlayerId =
              existingMatch.player_b_id;
          }
        }

        /*
         * If tied in an unknown stage,
         * there is no winner.
         */
        else {
          winnerTeamId =
            null;

          winnerPlayerId =
            null;
        }
      }
    }

    /*
     * --------------------------------------------------
     * 9. BUILD UPDATE
     * --------------------------------------------------
     */

    const updates = {
      score_team_a:
        scoreTeamA,

      score_team_b:
        scoreTeamB,

      status,

      winner_team_id:
        winnerTeamId,

      winner_player_id:
        winnerPlayerId,

      scheduled_date:
        body.scheduled_date ||
        null,

      scheduled_time:
        body.scheduled_time ||
        null,

      stream_link:
        body.stream_link ||
        null,

      notes:
        body.notes ||
        null,
    };

    console.log(
      "MATCH UPDATE DATA:",
      updates
    );

    /*
     * --------------------------------------------------
     * 10. UPDATE DATABASE
     * --------------------------------------------------
     */

    const {
      data: match,
      error,
    } = await supabase
      .from("matches")
      .update(updates)
      .eq("id", matchId)
      .select("*")
      .single();

    if (error) {
      console.error(
        "SUPABASE MATCH UPDATE ERROR:",
        error
      );

      return NextResponse.json(
        {
          success: false,
          message:
            error.message ||
            "Failed to update match.",
          error:
            error.message,
          details:
            error.details,
          hint:
            error.hint,
          code:
            error.code,
        },
        { status: 500 }
      );
    }

    if (!match) {
      return NextResponse.json(
        {
          success: false,
          message:
            "Match was not found after the update.",
        },
        { status: 404 }
      );
    }

    console.log(
      "MATCH UPDATED SUCCESSFULLY:",
      match
    );

    /*
     * --------------------------------------------------
     * 11. KNOCKOUT ADVANCEMENT
     * --------------------------------------------------
     *
     * CRITICAL:
     *
     * Round Robin NEVER advances a participant.
     *
     * Double-leg Round Robin NEVER advances a
     * participant.
     *
     * Only a true knockout match can advance.
     */

    let advancement:
      | {
          advanced: boolean;
          message: string;
          nextMatchId?: number;
          nextRound?: string;
        }
      | null = null;

    if (
      match.status?.toLowerCase() ===
        "completed" &&
      isKnockout
    ) {
      try {
        advancement =
          await advanceKnockoutMatch(
            match
          );

        console.log(
          "KNOCKOUT ADVANCEMENT RESULT:",
          advancement
        );
      } catch (
        advancementError
      ) {
        console.error(
          "KNOCKOUT ADVANCEMENT ERROR:",
          advancementError
        );

        return NextResponse.json(
          {
            success: false,

            message:
              "Match was completed, but the winner could not be advanced to the next knockout round.",

            match,

            advancement_error:
              advancementError instanceof Error
                ? advancementError.message
                : "Unknown advancement error.",
          },
          { status: 500 }
        );
      }
    }

    /*
     * --------------------------------------------------
     * 12. SUCCESS
     * --------------------------------------------------
     */

    return NextResponse.json({
      success: true,

      message:
        "Match updated successfully.",

      match,

      matchStage: {
        isRoundRobin,
        isKnockout,
      },

      advancement,
    });
  } catch (error) {
    console.error(
      "PATCH match API error:",
      error
    );

    return NextResponse.json(
      {
        success: false,

        message:
          error instanceof Error
            ? error.message
            : "Unexpected server error.",
      },
      { status: 500 }
    );
  }
}